export const url = "https://www.thirdbracket.co.uk";
// export const siteicon = "/icon.png";

// export const gtm = "GTM-XXXXXXX"
// export const gtmconnected = true

export const sitename = "Third Bracket";
export const description =
  "Step into Third Bracket Solutions, a UK-based modern web infrastructure development service born from the collective efforts of a group of nomads who conquered platforms like Upwork and Fiverr.";
export const keywords = [
  "custom web development company",
  "Manchester web agency",
  "Manchester seo agency",
  "Manchester web design",
  "Manchester digital agency",
  "Manchester digital marketing",
  "minimalist web development",
  "custom web development in manchester",
  "affordable web development in Manchester",
  "manchester branding agency",
  "wordpress developer manchester",
  "wordpress agency manchester",
  "nextjs developer manchester",
  "social media marketing agency manchester",
  "manchester ui ux design agency",
  "Free nextjs template",
  "Free nextjs boilerplate",
  "Free nextjs landing page template",
  "minimal Ui component library",
  "mega menu ux",
  "mega menu tailwind",
  "tailwind theme switcher",
  "react mega menu",
  "nextjs saas landing",
  "verify properties limited",
  "nextjs portfolio landing",
  "nextjs geolocation",
  "third bracket",
  "bracket ui",
  "nextjs property landing",
  "products of bangladesh",
  "notion blog",
  "best wordpress infrastructure",
  "affordable web development uk",
  "affordable custom web development",
  "custom web development company",
  "Manchester web agency",
  "Manchester seo agency",
  "Manchester web design",
  "Manchester digital agency",
  "Manchester digital marketing",
  "minimalist web development",
  "custom web development in manchester",
  "affordable web development in Manchester",
  "manchester branding agency",
  "wordpress developer manchester",
  "wordpress agency manchester",
  "nextjs developer manchester",
  "social media marketing agency manchester",
  "manchester ui ux design agency",
  "Free nextjs template",
  "Free nextjs boilerplate",
  "Free nextjs landing page template",
  "minimal Ui component library",
  "mega menu ux",
  "mega menu tailwind",
  "tailwind theme switcher",
  "react mega menu",
  "nextjs saas landing",
  "verify properties limited",
  "nextjs portfolio landing",
  "nextjs geolocation",
  "third bracket",
  "bracket ui",
  "nextjs property landing",
  "products of bangladesh",
  "notion blog, best wordpress infrastructure, affordable web development uk, affordable custom web development",
  "Third Bracket",
  "custom web development company",
  "Manchester web agency",
  "Manchester seo agency",
  "Manchester web design",
  "Manchester digital agency",
  "Manchester digital marketing",
  "minimalist web development",
  "custom web development in manchester",
  "affordable web development in Manchester",
  "manchester branding agency",
  "wordpress developer manchester",
  "wordpress agency manchester",
  "nextjs developer manchester",
  "social media marketing agency manchester",
  "manchester ui ux design agency",
  "Free nextjs template",
  "Free nextjs boilerplate",
  "Free nextjs landing page template",
  "minimal Ui component library",
  "mega menu ux",
  "mega menu tailwind",
  "tailwind theme switcher",
  "react mega menu",
  "nextjs saas landing",
  "verify properties limited",
  "nextjs portfolio landing",
  "nextjs geolocation",
  "third bracket",
  "bracket ui",
  "nextjs property landing",
  "products of bangladesh",
  "notion blog",
  "best wordpress infrastructure",
  "affordable web development uk",
  "affordable custom web development",
];
export const urlimage = "/og-image.png";
export const imagealt = "Third Bracket";
export const twitterhandle = "@ThirdbracketStudio";

export const companyname = "Third Bracket Studio";
export const companylink = "https://www.thirdbracket.co.uk";
