import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ThemeScript } from "@thirdbracket/bracketui";
import Header from "../../components/Header";
import SiteFooter from "../../components/Footer";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ThemeScript />
      </head>
      <body
        className={`${roboto.className} antialiased dark:bg-gray-950 dark:text-white`}
        suppressHydrationWarning
      >
        <Header />
        <main className="min-h-screen pt-16 lg:pt-24 dark:bg-gray-950 dark:text-white">
          {" "}
          {children}
        </main>
        <SiteFooter />{" "}
      </body>
    </html>
  );
}
